### ISSUE TITLE
FACeB2B El mensaje entrante se firmó con un token que era diferente del que solía cifrar el cuerpo. Esto no se esperaba.

### ISSUE THREAD

**Issue by JMLOSP** [xocapik/FaceWebServiceClient#1]
Buenas tardes, 

En primer lugar agradecerte el proyecto que has hecho, gracias a tus directrices fuí capaz de enlazar con los servicios web de FACeB2B.

Desconozco el motivo pero desde ayer me está apareciendo el siguiente mensaje:

**El mensaje entrante se firmó con un token que era diferente del que solía cifrar el cuerpo. Esto no se esperaba.**

¿Sabes a que puede ser debido? No he realizado ningún cambio en el codigo y me parece extraño que haya empezado a suceder derrepente. ¿Algun cambio en algún certificado?

Muchas gracias por tu proyecto y tu tiempo.

Saludos.

**Comment by xocapik** [comment]
Hola!
Pues han cambiado el certificado del servicio web y su identidad DNS
Según la web de ayuda entró en vigor el 18 de Enero de 2019 y estará vigente hasta Diciembre de 2021.
https://administracionelectronica.gob.es/ctt/faceb2b/descargas#.XGWOO6JKiyo

Si cambias los certificados y la identidad dns debería funcionar bien, aunque cuando yo lo probé solo me funciono el WS de producción, el de pruebas estaba offline

**Comment by JMLOSP** [comment]
Buenas @xocapik 

En primer lugar gracias por tu respuesta tan rapida y de nuevo gracias por tu ayuda.

Como el desarrollo lo empezamos recientemente el certificado nuevo ya era el que estabamos gastando, ya te digo que ayer por la mañana funcionaba todo OK y hoy no he conseguido hacerlo funcionar.

![imagen](https://user-images.githubusercontent.com/9148525/52800927-18679e80-307d-11e9-884b-a7b14d08c14a.png)

¿Has podido probarlo en PREPRODUCCIÓN y ver si te funciona bien?

Gracias.
Saludos.

**Comment by JMLOSP** [comment]
Buenos días, he estado con el fiddler trazando las devoluciones y veo que están devolviendo las respuestas en Preproducción con un certificado caducado.

![certificadofaceb2b](https://user-images.githubusercontent.com/9148525/52840866-dd0bb500-30fa-11e9-9340-06174b11fadb.png)

Les he dado de alta la incidencia para ver que me comentan, imagino que este es el verdadero origen del problema.

Dejo la issue cerrada por que en Producción funciona todo OK y esto es completamente ajeno a tu codigo e indicaciones. 

Muchas gracias por tu ayuda y disculpa las molestias.
Saludos.
